[book]
authors = ["Dmitri Lyalikov Iñigo Lara Izcue Francesco J. Sheiban"]
language = "en"
multilingual = false
src = "docs"
title = "Axon SDK Documentation"

[output.html]
mathjax-support = true
default-theme = "light"
smart-punctuation = true
git-repository-url = "https://github.com/existential-ai/axon-sdk.github.io/tree/axon-package"
edit-url-template = "https://github.com/existential-ai/axon-sdk.github.io/tree/axon-package/{path}"

[output.html.fold]
enable = true
level = 0
