name: Build Package

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Confirm working directory
        run: pwd

      - name: Show all pyproject.toml locations
        run: find . -name pyproject.toml

      - name: Show pyproject.toml
        run: cat pyproject.toml

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the distribution
        run: |
          python -m build
          ls -lh dist/

      - name: Validate distribution metadata
        run: |
          twine check dist/*
