name: Run tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  test:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests and generate report
      run: |
        pytest -v stick-emulator/test_imn.py --html=report.html
      working-directory: ${{ github.workspace }}

    - name: Save test report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.html
